# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39811e485322a07f26843561d7c4b788485ae755aa0c853e3d58592cfdddf7663f7e260550bcaaa3e6c645a2a63992cda66eefd5902a34cede3e18ef9b309b7a

test:
  secret_key_base: 9d10e9c4074b64de0bf6ba2caf3d1d9e3aa2be3dde9248e61ac01359e57bd64a788c7caef9c38c5b1b162c5c5d0cc632c11e35ab95305a2541fe6b8ab17e3366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
